#!/bin/bash
#https://www.ionos.com/community/server-cloud-infrastructure/docker/understanding-and-managing-docker-container-volumes/
#https://docker-curriculum.com/
#https://severalnines.com/database-blog/mysql-docker-containers-understanding-basics
#https://hub.docker.com/_/mysql/