#!/bin/bash
#Create an overlay-type internal network that you will name overmind.
docker network create -d overlay overmind

#Source
#https://docs.docker.com/network/overlay/
#https://docs.docker.com/engine/reference/commandline/network_create/